default_stages: [commit, manual]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-executables-have-shebangs
        # This hook has issues on Windows, don't use it in manual mode
        stages: [commit]
      - id: check-shebang-scripts-are-executable
        # This hook has issues on Windows, don't use it in manual mode
        stages: [commit]
      - id: check-symlinks
      - id: mixed-line-ending
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
      - id: cmake-lint
  # Local clang-format hook for manual mode
  - repo: https://github.com/doublify/pre-commit-clang-format
    rev: 62302476d0da01515660132d76902359bed0f782
    hooks:
      - id: clang-format
        stages: [manual]
        types:
          - c++
  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
      -   id: pyupgrade
          args: [--py36-plus]
  -   repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v2.0.2
      hooks:
      -   id: autopep8
          args: [--in-place, --aggressive, --global-config, setup.cfg]
  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
      -   id: isort
          args: [--settings, setup.cfg]
  -   repo: https://github.com/asottile/add-trailing-comma
      rev: v3.1.0
      hooks:
      -   id: add-trailing-comma
          args: [--py36-plus]
  -   repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
      -   id: flake8
          additional_dependencies: [
              darglint==1.8.1,
              flake8-2020==1.7.0,
              flake8-alfred==1.1.1,
              flake8-builtins==2.1.0,
              flake8-logging-format==0.9.0,
              flake8-mutable==1.2.0,
              flake8-pytest-style==1.7.2,
              flake8-use-fstring==1.4,
              flake8-expression-complexity==0.0.11,
              flake8-variables-names==0.0.5,
              flake8-pyi==23.3.1,
              bandit==1.7.5,
          ]
